### PR TITLE
fix: Remove blurry antialiasing

### LINKED ISSUE #98: `will-change: transform` makes keyboard very blurry
**Describe the bug**
Zooming in on the Keyboard makes the keys very blurry, both the fonts for the letters inside and the background itself. Removing the `will-change: transform` property fixes this issue.

**To Reproduce**
I've initially had this happen on the standalone app, however, it also applies on the storybook:
1. Launch the storybook, on the Keyboard > PhysicalLayout > Docs page
2. Click the "zoom" button
3. See that the keys are visibly antialiased
4. If any keys are hovered, they'll revert back to a non-blurry version after the animation

**Expected behavior**
Keys should be clear, and if there's any antialiasing, it shouldn't be super noticeable.

**Screenshots**
image
image
image

**Environment (please complete the following information):**
 - OS: MacOS
 - Browser or App: Chromium or standalone MacOS ARM application (Webkit?)
 - Version: Currently on main (v0.2.4)
 - Device: N/A

**Additional context**
N/A

### PR DESCRIPTION
**Pull request by filiptdz**
Fixes https://github.com/zmkfirmware/zmk-studio/issues/98

### CODE REVIEW

**Review by Nicell — COMMENTED** [review]
This property was originally added to fix AA on rotated keys according to this: https://github.com/zmkfirmware/zmk-studio/commit/899c3556b8ca5c87434912afbd19d109cd26ac7d

I'm interested where you're seeing the blurriness from. I couldn't recreate it using the keymap zoom in the top right or by doing a `cmd+` or pinching my fingers. I can recreate it in storybook using that zoom, but I'm not sure what it's doing?

**Comment by filiptdz** [comment]
@Nicell thanks! yeah I saw the other commit, and figured there was a specific reason for it, although I couldn't find it. I'm curious whether there's another workaround for that.

I can see the blurriness on the https://zmk.studio website by setting the scale on the top right corner to 25%, reloading the page, and then setting it to 200%.

I saw it initially on the standalone MacOS application, by resizing the window. However, there even hovering a key with the mouse doesn't force it to re-render without being blurry, so I'm not sure if the fix would work the same way

**Comment by pongstr** [comment]
👋🏽 @filiptdz this PR #108 might interest you, it eliminates the blurring issue and improves the scale transition

**Comment by filiptdz** [comment]
@pongstr that does solve the issue and looks extremely clean, I'll close my PR in favor of yours

thanks for bringing this to my attention 😁

**Pull request closed without merging**
